### ISSUE TITLE
При совершении оплаты с кредитного счёта на большую сумму, баланс не меняется

### ISSUE THREAD

**Issue by Bob-Jacka** [Bob-Jacka/JavaForTesters#24]
# Описание
При совершении оплаты со счёта на большую сумму, баланс счёта не меняется.

## Локация дефекта
https://github.com/Bob-Jacka/JavaForTesters/blob/100d636541bb8c98dc738d26d6e1c2e16ca61a34/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L47

## Шаги воспроизведения
1. Создать объект класса CreditAccount со значениями переменных `creditLimit` = 50, `rate` = 50
2. Совершить оплату с кредитного счёта на большую сумму (например 600_000)

_Ожидаемый результат:_ Операция проходит успешно, сумма вычитается из баланса.
_Фактический результат:_ Операция не проходит, сумма не вычитается из баланса.

## Тест для проверки
https://github.com/Bob-Jacka/JavaForTesters/blob/100d636541bb8c98dc738d26d6e1c2e16ca61a34/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L223

## Скриншот
![Screenshot from 2023-06-15 13-47-50](https://github.com/Bob-Jacka/JavaForTesters/assets/126481207/3fd6de6f-e641-47bf-835b-8198c459c135)

## Окружение

- **Операционная система** Linux 6.2.12-arch1-1
- **IDEA** IntelliJ IDEA 2023.1 (Community Edition)
- **Java** JDK 11 corretto-11.0.19

**Comment by Shapokula** [comment]
В требованиях к классу есть условие:
https://github.com/Bob-Jacka/JavaForTesters/blob/100d636541bb8c98dc738d26d6e1c2e16ca61a34/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L5

В данном тесте при попытке оплаты результат выходит за обозначенный предел:
https://github.com/Bob-Jacka/JavaForTesters/blob/100d636541bb8c98dc738d26d6e1c2e16ca61a34/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L51

Бага нет.
